### ISSUE TITLE
[Render] Center content

### ISSUE THREAD

**Issue by RaphaelPour** [RaphaelPour/blogctl#105]
```css
body {
  margin-right: auto;
  margin-left: auto;
  max-width: 960px;
}
```
